### Check server
GET http://localhost:3000/check
Accept: application/json

###

### Register a user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "test@sand.com",
  "password": "test123"
}

###

### Login the user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "test@sand.com",
  "password": "test123"
}

###

### Testing
POST http://localhost:3000/api/creations
Content-Type: application/json
Authorization: Bearer <PASTE_TOKEN_HERE>

{
  "imagePath": "test-image-path.png"
}
